"""Typed models for artifacts, configuration, results and events."""

from rote.schema.capability import (
    Capability,
    CheckStep,
    ClickStep,
    ExtractStep,
    FillStep,
    InputSpec,
    OutcomeSpec,
    OutputSpec,
    PressStep,
    ProductRef,
    ProvenanceInfo,
    SelectStep,
    Step,
    dump_capability,
    load_capability,
    save_capability,
)
from rote.schema.condition import Condition
from rote.schema.config import (
    Approval,
    InterruptSpec,
    Limits,
    Policy,
    ProductProfile,
    RiskRule,
    TenantConfig,
)
from rote.schema.result import ErrorInfo, OutcomeInfo, RunResult
from rote.schema.target import CssLocator, LabelLocator, RoleLocator, TableCellLocator, Target

__all__ = [
    "Approval",
    "Capability",
    "CheckStep",
    "ClickStep",
    "Condition",
    "CssLocator",
    "ErrorInfo",
    "ExtractStep",
    "FillStep",
    "InputSpec",
    "InterruptSpec",
    "LabelLocator",
    "Limits",
    "OutcomeInfo",
    "OutcomeSpec",
    "OutputSpec",
    "Policy",
    "PressStep",
    "ProductProfile",
    "ProductRef",
    "ProvenanceInfo",
    "RiskRule",
    "RoleLocator",
    "RunResult",
    "SelectStep",
    "Step",
    "TableCellLocator",
    "Target",
    "TenantConfig",
    "dump_capability",
    "load_capability",
    "save_capability",
]
